services:
   _defaults:
      autoconfigure: true
      autowire: true
      public: true

   Cgoit\ContaoFolderGalleryDownloadExtensionBundle\:
      resource: ../src
      exclude: ../src/{ContaoManager,DependencyInjection,Event,CgoitFolderGalleryDownloadExtensionBundle.php}
